### ISSUE TITLE
pluralchum could not be started

### ISSUE THREAD

**Issue by gaysaito** [estroBiologist/pluralchum#11]
TypeError: Modules is not iterable
    at Pluralchum.forceMessageRefresh (eval at requireAddon (:4:43355), <anonymous>:225:26)
    at Pluralchum.start (eval at requireAddon (:4:43355), <anonymous>:218:10)
    at Object.startPlugin (<anonymous>:4:43903)
    at Object.startAddon (<anonymous>:4:43696)
    at Object.enableAddon (<anonymous>:4:10436)
    at Object.toggleAddon (<anonymous>:4:10681)
    at Object.togglePlugin (<anonymous>:4:41036)
    at A.onChange (<anonymous>:4:101873)
    at m.onChange (<anonymous>:4:96985)
    at Object.Ye (https://discord.com/assets/2417af15fabc622ecc0f.js:1453:658)
    at qe (https://discord.com/assets/2417af15fabc622ecc0f.js:1453:812)
    at https://discord.com/assets/2417af15fabc622ecc0f.js:1473:409
    at Pr (https://discord.com/assets/2417af15fabc622ecc0f.js:1473:506)
    at Mr (https://discord.com/assets/2417af15fabc622ecc0f.js:1473:920)
    at https://discord.com/assets/2417af15fabc622ecc0f.js:1479:680
    at Ge (https://discord.com/assets/2417af15fabc622ecc0f.js:1561:404)
    at https://discord.com/assets/2417af15fabc622ecc0f.js:1475:395
    at Br (https://discord.com/assets/2417af15fabc622ecc0f.js:1475:425)
    at rn (https://discord.com/assets/2417af15fabc622ecc0f.js:1462:757)
    at nn (https://discord.com/assets/2417af15fabc622ecc0f.js:1462:7)
    at t.unstable_runWithPriority (https://discord.com/assets/2417af15fabc622ecc0f.js:1662:828)
    at Ko (https://discord.com/assets/2417af15fabc622ecc0f.js:1484:117)
    at we (https://discord.com/assets/2417af15fabc622ecc0f.js:1561:144)
    at en (https://discord.com/assets/2417af15fabc622ecc0f.js:1461:800)
    at HTMLDivElement.r (https://discord.com/assets/40b8dd053309f0ba5d75.js:145:559)

**Comment by estroBiologist** [comment]
Discord just pushed out a massive change to its internals that breaks practically every BetterDiscord plugin out there, PluralChum included. Nothing I can do about it at the moment. Might take a rewrite to get PC working again, which I can't give an ETA for. See https://github.com/BetterDiscord/BetterDiscord/issues/1404#issuecomment-1258808958 for more info.
