### ISSUE TITLE
"PluralChum could not be started"

### ISSUE THREAD

**Issue by llangdxn** [estroBiologist/pluralchum#50]
I've been getting this error everytime i try to turn on the PC plugin manually in the plugins menu of betterdiscord because PC doesn't turn on by itself like my other plugins. 
I've tried uninstalling and reinstalling the plugin multiple times to make sure i had to most up to date version, i've tried uninstalling and reinstalling the plugin library as well, and i've even done the 'repair better discord' thing that pops up when you open the installer. 
I had this issue once before, but simply uninstalling and reinstalling the plugin a few times fixed the issue, but now nothing seems to work. This issue usually pops up whenever discord updates itself.
Attached is a video of me trying to turn the plugin on, and the plugin library works just fine, so i have no idea why pluralchum just refuses to turn on. I really enjoy using PC so it sucks that i keep running into this issue.
https://github.com/user-attachments/assets/707a380c-1755-487b-81e5-6ff55b4c41cc

**Comment by MegaShinySnivy** [comment]
Can confirm, this is an issue for me.

**Comment by viiuan** [comment]
```
Pluralchum v2.5.0 could not be started. TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at patchMessageHeader (Pluralchum.plugin.js:24393:10)
    at Pluralchum.start (Pluralchum.plugin.js:24811:5)
    at N.startPlugin (renderer.js:5:50638)
    at N.startAddon (renderer.js:5:50431)
    at N.enableAddon (renderer.js:5:13676)
    at N.toggleAddon (renderer.js:5:14475)
    at N.togglePlugin (renderer.js:5:47719)
    at renderer.js:5:130011
    at renderer.js:5:169700
    at Object.eH (web.287201c4becdf332.js:12:1110728)
    at eQ (web.287201c4becdf332.js:12:1110882)
    at eX (web.287201c4becdf332.js:12:1110939)
    at ry (web.287201c4becdf332.js:12:1132028)
    at rO (web.287201c4becdf332.js:12:1132444)
    at web.287201c4becdf332.js:12:1137341
    at s8 (web.287201c4becdf332.js:12:1202666)
    at eB (web.287201c4becdf332.js:12:1109869)
    at rC (web.287201c4becdf332.js:12:1133735)
    at t$ (web.287201c4becdf332.js:12:1118085)
    at tX (web.287201c4becdf332.js:12:1117869)
stacktrace @ renderer.js:5
startPlugin @ renderer.js:5
startAddon @ renderer.js:5
enableAddon @ renderer.js:5
toggleAddon @ renderer.js:5
togglePlugin @ renderer.js:5
(anonymous) @ renderer.js:5
(anonymous) @ renderer.js:5
eH @ web.287201c4becdf332.js:12
eQ @ web.287201c4becdf332.js:12
eX @ web.287201c4becdf332.js:12
ry @ web.287201c4becdf332.js:12
rO @ web.287201c4becdf332.js:12
(anonymous) @ web.287201c4becdf332.js:12
s8 @ web.287201c4becdf332.js:12
eB @ web.287201c4becdf332.js:12
rC @ web.287201c4becdf332.js:12
t$ @ web.287201c4becdf332.js:12
tX @ web.287201c4becdf332.js:12
VM232 C:\Users\user\AppData\Local\Discord\app-1.0.9187\modules\discord_desktop_core-1\discord_desktop_core\core.asar\app\node_modules\@sentry\utils\cjs\instrument\fetch.js:45 Fetch API cannot load sentry-ipc://sentry-electron.scope/sentry_key. URL scheme "sentry-ipc" is not supported.
```
info in console when i get the same error
